#pragma once

#define LILA_PLATFORM_VALUE_UNKNOWN 0
#define LILA_PLATFORM_VALUE_WINDOWS 1
#define LILA_PLATFORM_VALUE_LINUX   2
#define LILA_PLATFORM_VALUE_ANDROID 3
#define LILA_PLATFORM_VALUE_MACOS   4
#define LILA_PLATFORM_VALUE_IOS     5

#if defined(WIN32) || defined(_WIN32) || defined(__WIN32__)
#ifndef _WIN64
#error "64-bit is required"
#endif
#define LILA_PLATFORM_WINDOWS 1
#define LILA_ACTIVE_PLATFORM LILA_PLATFORM_VALUE_WINDOWS
#elif defined(__ANDROID__)
#define LILA_PLATFORM_ANDROID 1
#define LILA_ACTIVE_PLATFORM LILA_PLATFORM_VALUE_ANDROID
#elif defined(__linux__) || defined(__gnu_linux__)
#define LILA_PLATFORM_LINUX 1
#define LILA_ACTIVE_PLATFORM LILA_PLATFORM_VALUE_LINUX
#elif __APPLE__
#define LILA_PLATFORM_APPLE 1
#include <TargetConditionals.h>
#if TARGET_IPHONE_SIMULATOR
#define LILA_PLATFORM_IOS 1
#define LILA_PLATFORM_IOS_SIM 1
#define LILA_ACTIVE_PLATFORM LILA_PLATFORM_VALUE_IOS
#elif TARGET_OS_PHONE
#define LILA_PLATFORM_IOS 1
#define LILA_ACTIVE_PLATFORM LILA_PLATFORM_VALUE_IOS
#elif TARGET_OS_MAC
#define LILA_PLATFORM_MACOS 1
#define LILA_ACTIVE_PLATFORM LILA_PLATFORM_VALUE_MACOS
#else
#error "Unknown Apple platform"
#endif
#else
#define LILA_ACTIVE_PLATFORM LILA_PLATFORM_VALUE_UNKNOWN
#error "Unknown platform"
#endif
