name: 🌸 Continuous integration

on: [ push, pull_request ]

jobs:
  static-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
        
      - name: Spell Check
        uses: codespell-project/actions-codespell@v2
        with:
          skip: ./bin,./doc,./docs/CODE_OF_CONDUCT.md,./deps,*.txt,*.yml.*.json,*.toml,*.ini,*.xml
          check_filenames: true

  build-linux:
    runs-on: ubuntu-latest
    needs: static-tests
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Downloading X11
      run: sudo apt install xorg-dev

    - name: Downloading Premake
      uses: BEASTSM96/premake-action@v1.3.1

    - name: Using Premake
      run: premake5 gmake2 --headless
    
    - name: Build using Make
      run: make config=debug
      
  build-windows:
    runs-on: windows-latest
    needs: static-tests
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - name: Configure MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Downloading Premake
      uses: BEASTSM96/premake-action@v1.3.1

    - name: Using Premake
      run: premake5 vs2022 --headless
    
    - name: Build using MSBuild
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug .
    
  test-linux:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Downloading X11
      run: sudo apt install xorg-dev

    - name: Downloading Premake
      uses: BEASTSM96/premake-action@v1.3.1

    - name: Using Premake
      run: premake5 gmake2 --headless
    
    - name: Build using Make
      run: make config=debug

    - name: Run
      run: |
        cd bin/linux-x86_64/Debug/Testbed
        ./Testbed
        cd ../../../../
        
  test-windows:
    runs-on: windows-latest
    needs: build-windows
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - name: Configure MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Downloading Premake
      uses: BEASTSM96/premake-action@v1.3.1

    - name: Using Premake
      run: premake5 vs2022 --headless
    
    - name: Build using MSBuild
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug .
      
    - name: Run
      run: |
        cd bin/windows-x86_64/Debug/Testbed
        ./Testbed
        cd ../../../../
